### ISSUE TITLE
[Readme related] defer command in Configuration section

### ISSUE THREAD

**Issue by greenfork** [andreyorst/fzf.kak#59]
Hello, I don't understand this thing in Configuration section of readme: so in order to change variable values use defer "fzf %{ ... }". `defer` is not bash command, not kakoune command, not in the source of plug.kak, what is it?

PS there's also a typo "requier-module fzf" -> "require-module fzf"

**Comment by greenfork** [comment]
Oh well of course it's in the `plug.kak` `dev` branch, now I see it.

**Comment by andreyorst** [comment]
> Oh well of course it's in the `plug.kak` `dev` branch, now I see it.

Yes, since this plugin requires latest version of Kakoune, you also need `dev` version of plug.kak to use.



> Configuration section of readme: so in order to change variable values use defer "fzf %{ ... }". `defer` is not bash command, not kakoune command, not in the source of plug.kak, what is it?

Basically the commands under the `defer` section will be run after module was required. `fzf` command requires the module when you first run it, so you need only a mapping to be configured at startup.

**Comment by greenfork** [comment]
Thank you for answering!
